# Generated by Django 6.0.6 on 2026-06-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('card_type', models.CharField(choices=[('EX', 'Exercise'), ('MI', 'Mistake'), ('CO', 'Concept'), ('NO', 'Note'), ('QU', 'Question')], default='QU', max_length=2)),
                ('review_method', models.CharField(choices=[('RC', 'Recall'), ('TS', 'Test'), ('RD', 'Read'), ('WT', 'Watch')], default='RC', max_length=2)),
                ('attached_file', models.URLField(blank=True, null=True)),
                ('context_hint', models.TextField(blank=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('stability', models.FloatField(default=0)),
                ('difficulty', models.FloatField(default=0)),
                ('elapsed_days', models.IntegerField(default=0)),
                ('scheduled_days', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card.topic')),
            ],
        ),
    ]
