# Generated by Django 6.0.6 on 2026-07-01 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='card_audio/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='card_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')])),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('review_duration_ms', models.IntegerField(help_text='How long it took the user to answer in milliseconds')),
                ('due', models.DateTimeField()),
                ('stability', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('elapsed_days', models.IntegerField()),
                ('scheduled_days', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='card.card')),
            ],
        ),
    ]
