# Generated by Django 6.0.6 on 2026-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_audio_alter_card_attached_file_alter_card_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
