# Generated by Django 6.0.6 on 2026-07-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlog',
            old_name='card',
            new_name='card_id',
        ),
    ]
