# Generated by Django 6.0.6 on 2026-07-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_rename_card_reviewlog_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='guest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='guest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest', models.CharField(max_length=100, null=True)),
                ('exam_name', models.TextField()),
                ('dead_line', models.DateField()),
                ('desired_retention', models.FloatField(default=0.9)),
                ('priority', models.FloatField(default=1)),
                ('topics', models.ManyToManyField(related_name='exams', to='card.topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='card.user')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card.user'),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='card.user'),
        ),
    ]
