# Generated by Django 6.0.6 on 2026-07-07 10:59

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_user_card_guest_topic_guest_exam_card_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=card.models.default_parameters, help_text='FSRS parameter list used to initialize the scheduler.')),
                ('desired_retention', models.FloatField(default=0.9)),
                ('learning_steps', models.JSONField(default=card.models.default_learning_steps)),
                ('relearning_steps', models.JSONField(default=card.models.default_relearning_steps)),
                ('maximum_interval', models.IntegerField(default=36500)),
                ('enable_fuzzing', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card_limit', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'FSRS Scheduler',
                'verbose_name_plural': 'FSRS Schedulers',
            },
        ),
    ]
