# Generated by Django 6.0.6 on 2026-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_scheduler_settings_user_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_settings',
            name='card_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduler_settings',
            name='guest',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='scheduler_settings',
            unique_together={('user', 'guest')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('guest', 'topic_name')},
        ),
    ]
