# Generated by Django 6.0.6 on 2026-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_scheduler_settings_card_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=1),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='state',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')]),
        ),
    ]
