# Generated by Django 6.0.6 on 2026-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_card_state_alter_reviewlog_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
