# Generated by Django 6.0.6 on 2026-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_card_step'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='card',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('user', 'guest'), name='unique_user_guest_topic'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('user', 'topic_name'), name='unique_user_topicname'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('guest', 'topic_name'), name='unique_guest_topicname'),
        ),
    ]
