# Generated by Django 6.0.6 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_topic_unique_together_alter_card_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='stability',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
